version: '3.8'

services:
  kafka:
    image: apache/kafka-native:3.9.0
    container_name: kafka
    networks:
      - fraud-detection
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=HOST://localhost:9092,DOCKER://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9091
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  ml:
    build: 
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml
    networks:
      - fraud-detection
    ports:
      - "5000:5000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - fraud-detection
    ports:
      - "5001:5001"
    environment:
      - ENV=prod
    depends_on:
      - kafka

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - fraud-detection
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  fraud-detection:
    driver: bridge
