apiVersion: apps/v1
kind: Deployment
metadata:
  name: onnx-runtime-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onnx-api
  template:
    metadata:
      labels:
        app: onnx-api
    spec:
      containers:
      - name: onnx-container
        image: torontoms/onnx-rest-api:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
