name: CI/CD Pipeline

on:  
  push:  
    branches:  
      - main       # Run workflow when code is pushed to 'main' branch
  pull_request:  
    branches:  
      - main

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest  # Runner: Ubuntu VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: build-and-test  # Run this job after 'build-and-test' passes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t torontoms/onnx-rest-api:latest ./onnx/.

      - name: Push Docker image
        run: |
          docker push torontoms/onnx-rest-api:latest
